config/routes.rb
Ishmenu::Engine.routes.draw do
  

  resources :menus, :path => '/' do
  	resources :menu_items, :path => '/items', :as => 'items'
  end

end

app/models/ishmenu/menu.rb
module Ishmenu
  class Menu < ActiveRecord::Base

  		# This assumes you already have friendly_id in your gemfile and all that good stuff.
  		extend FriendlyId
  		friendly_id :slug, use: :slugged

  		# Association
  		has_many :menu_items, dependent: :destroy

  		# Fields validation
  		SLUG_REGEX = /\A^[\w&-]+$\Z/

  		validates :name, presence: true,
  		            length: { maximum: 250 }

  		validates :slug, presence: true,
			  		uniqueness: true,
  		            length: { maximum: 250 },
  		            format: SLUG_REGEX

  end
end

app/models/ishmenu/menu_item.rb
module Ishmenu
  class MenuItem < ActiveRecord::Base

  	# Association
  	belongs_to :menu

  	# Scope
  	scope :sorted, lambda { order(priority: :asc) }

  end
end

app/controllers/ishmenu/application_controller.rb
module Ishmenu
  class ApplicationController < ::ApplicationController
  end
end

app/controllers/ishmenu/menu_items_controller.rb
require_dependency "ishmenu/application_controller"

module Ishmenu
  class MenuItemsController < ApplicationController
    before_action :set_menu_item, only: [:edit, :update, :destroy]
    before_action :authenticate_user!
    before_action :load_menu

    layout 'application'

    # GET /menu_items
    def index
      redirect_to menu_path(@menu)
    end


    # GET /menu_items/new
    def new
      @menu_item = MenuItem.new
    end

    # GET /menu_items/1/edit
    def edit
    end

    # POST /menu_items
    def create
      @menu_item = MenuItem.new(menu_item_params)

      if @menu_item.save
        redirect_to menu_path(@menu), notice: 'Menu item was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /menu_items/1
    def update
      if @menu_item.update(menu_item_params)
        redirect_to menu_path(@menu), notice: 'Menu item was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /menu_items/1
    def destroy
      @menu_item.destroy
      redirect_to :back, notice: 'Menu item was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_menu_item
        @menu_item = MenuItem.find(params[:id])
      end

      def load_menu
        @menu = Menu.friendly.find(params[:menu_id])
      end

      # Only allow a trusted parameter "white list" through.
      def menu_item_params
        params.require(:menu_item).permit(:menu_id, :title, :slug, :target, :item_id, :item_class, :priority)
      end
  end
end

app/controllers/ishmenu/menus_controller.rb
require_dependency "ishmenu/application_controller"

module Ishmenu
  class MenusController < ApplicationController
    before_action :set_menu, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!

    layout 'application'

    # GET /menus
    def index
      @menus = Menu.all
    end

    # GET /menus/1
    def show
    end

    # GET /menus/new
    def new
      @menu = Menu.new
    end

    # GET /menus/1/edit
    def edit
    end

    # POST /menus
    def create
      @menu = Menu.new(menu_params)

      if @menu.save
        redirect_to @menu, notice: 'Menu was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /menus/1
    def update
      if @menu.update(menu_params)
        redirect_to @menu, notice: 'Menu was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /menus/1
    def destroy
      @menu.destroy
      redirect_to menus_url, notice: 'Menu was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_menu
        @menu = Menu.friendly.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def menu_params
        params.require(:menu).permit(:name, :slug)
      end
  end
end

app/helpers/ishmenu/application_helper.rb
module Ishmenu
  module ApplicationHelper
  	def load_ishmenu_item(menu_item)
  		if !menu_item.target
  			content_tag :li, :class => get_ishmenu_item_class(menu_item) do
	  			link_to menu_item.title, menu_item.slug,  :target => '_blank'
	  		end
  		else
  			content_tag :li, :class => get_ishmenu_item_class(menu_item) do
	  			link_to menu_item.title, menu_item.slug, :target => '_self'
	  		end
  		end
  	end

  	def get_ishmenu_item_class(menu_item)
  		if current_page?(menu_item.slug)
	  		'active'
  		end
  	end
  end
end

app/helpers/ishmenu/menu_items_helper.rb
module Ishmenu
  module MenuItemsHelper
  	def load_ishmenu_item(menu_item)
  		if !menu_item.target
  			content_tag :li do
	  			link_to menu_item.title, menu_item.slug,  :target => '_blank'
	  		end
  		else
  			content_tag :li do
	  			link_to menu_item.title, menu_item.slug, :target => '_self'
	  		end
  		end
  	end
  end
end

app/helpers/ishmenu/menus_helper.rb
module Ishmenu
  module MenusHelper
  end
end

app/views/ishmenu/menu_items/_form.html.erb
<% if @menu_item.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@menu_item.errors.count, "error") %> prohibited this menu_item from being saved:</h2>

    <ul>
    <% @menu_item.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="field form-group">
  <%= f.label :menu %>
  <%= f.collection_select :menu_id, Ishmenu::Menu.all, :id, :name, { :required => true, :include_blank => false }, { :class => 'form-control' } %>
</div>

<div class="field form-group">
  <%= f.label :title %>
  <%= f.text_field :title, { :required => true, :id => 'title', :class => 'form-control' } %>
</div>
<div class="field form-group">
  <%= f.label :slug %>
  <%= f.text_field :slug, { :required => true, :id => 'slug', :class => 'form-control' } %>
</div>
<div class="field form-group">
  <%= f.label :target %>
  <%= f.select :target, options_for_select([['Same Window', true], ['New Window', false]], @menu_item.target) %>
</div>
<div class="field form-group">
  <%= f.label 'Item Id' %>
  <%= f.text_field :item_id, { :id => 'id', :class => 'form-control' } %>
</div>
<div class="field form-group">
  <%= f.label :item_class %>
  <%= f.text_field :item_class, { :id => 'class', :class => 'form-control' } %>
</div>
<div class="field form-group">
  <%= f.label :priority %>
  <%= f.number_field :priority, { :id => 'priority', :class => 'form-control' } %>
</div>
<div class="actions form-group">
  <%= f.submit :class => 'btn btn-primary' %>
</div>

app/views/ishmenu/menu_items/edit.html.erb
<h1>Editing Menu Item</h1>

<%= form_for(:menu_item, :url => menu_item_path(@menu, @menu_item), :html => { :role => 'form', :method => :patch}) do |f| %>

	<%= render :partial => 'form', :locals => { :f => f } %>

<% end %>

<%= link_to 'Back', menu_items_path %>

app/views/ishmenu/menu_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Menu Items</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Slug</th>
      <th>Target</th>
      <th>Id</th>
      <th>Class</th>
      <th>Priority</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @menu_items.each do |menu_item| %>
      <tr>
        <td><%= menu_item.title %></td>
        <td><%= menu_item.slug %></td>
        <td><%= menu_item.target %></td>
        <td><%= menu_item.id %></td>
        <td><%= menu_item.class %></td>
        <td><%= menu_item.priority %></td>
        <% if can? :update, menu_item %>
          <td><%= link_to 'Edit', edit_menu_item_path(menu_item) %></td>
        <% end %>
        <% if can? :destroy, menu_item %>
          <td><%= link_to 'Destroy', menu_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% if can? :create, Ishmenu::MenuItem %>
  
<% end %>
<%= link_to 'New Menu item', new_menu_item_path %>

app/views/ishmenu/menu_items/new.html.erb
<h1>New Menu Item</h1>

<%= form_for(:menu_item, :url => { :action => 'create' }, :html => { :role => 'form'}) do |f| %>
	<%= render :partial => 'form', :locals => { :f => f } %>
<% end %>
<%= link_to 'Back', menu_items_path %>

app/views/ishmenu/menu_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @menu_item.title %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @menu_item.slug %>
</p>

<p>
  <strong>Target:</strong>
  <%= @menu_item.target %>
</p>

<p>
  <strong>Id:</strong>
  <%= @menu_item.id %>
</p>

<p>
  <strong>Class:</strong>
  <%= @menu_item.class %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @menu_item.priority %>
</p>

<% if can? :update, @menu_item %>
  
<%= link_to 'Edit', edit_menu_item_path(@menu_item) %> |
<% end %>
<%= link_to 'Back', menu_items_path %>

app/views/ishmenu/menus/_form.html.erb
<%= form_for(@menu) do |f| %>
  <% if @menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% @menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %>
    <%= f.text_field :name, { :required => true, :id => 'title', :class => 'form-control' } %>
  </div>
  <div class="field form-group">
    <%= f.label :slug %>
    <%= f.text_field :slug, { :required => true, :id => 'slug', :class => 'form-control' } %>
  </div>
  <div class="actions form-group">
    <%= f.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/ishmenu/menus/_load_menu.html.erb
<% ishmenu = Ishmenu::Menu.find_by(slug: menu) %>

<% ishmenu.menu_items.each do |menu_item| %>
	<%= load_ishmenu_item(menu_item) %>
<% end %>

app/views/ishmenu/menus/edit.html.erb
<h1>Editing Menu</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/ishmenu/menus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Menus</h1>

<% if can? :create, Ishmenu::Menu %>
  <div class="clearfix">
    <p class="pull-right">
      <%= link_to 'New Menu', new_menu_path, :class => 'btn btn-primary' %>
    </p>
  </div>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menus.each do |menu| %>
      <tr>
        <td><%= menu.name %></td>
        <td><%= menu.slug %></td>
        <td><%= link_to 'Show', menu %></td>
        <% if can? :update, menu %>
          <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
        <% end %>
        <% if can? :destroy, menu %>
          <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/ishmenu/menus/new.html.erb
<h1>New Menu</h1>

<%= render 'form' %>

<%= link_to 'Back', menus_path %>

app/views/ishmenu/menus/show.html.erb
<p id="notice"><%= notice %></p>

<div class="well clearfix">
  <p>
    <strong>Name:</strong> <%= @menu.name %> <strong>Slug:</strong> <%= @menu.name %>
  
    <span class="pull-right">
      <% if can? :update, @menu %>
        <%= link_to 'Edit', edit_menu_path(@menu), :class => 'btn btn-xs btn-warning' %>
      <% end %>
      <% if can? :destroy, @menu %>
        <%= link_to 'Destroy', @menu, :class => 'btn btn-xs btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </span>
  </p>
</div>

<% if can? :create, Ishmenu::MenuItem %>
  <div class="clearfix">
    <p class="pull-right">
      <%= link_to 'Add menu item', new_menu_item_path(@menu), :class => 'btn btn-primary' %>
    </p> 
  </div>
<% end %>

<table class="table striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Slug</th>
      <th>Target</th>
      <th>Id</th>
      <th>Class</th>
      <th>Priority</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @menu.menu_items.each do |menu_item| %>
      <tr>
        <td><%= menu_item.title %></td>
        <td><%= menu_item.slug %></td>
        <td><%= menu_item.target %></td>
        <td><%= menu_item.item_id %></td>
        <td><%= menu_item.item_class %></td>
        <td><%= menu_item.priority %></td>
        <% if can? :update, menu_item %>
          <td><%= link_to 'Edit', edit_menu_item_path(@menu, menu_item) %></td>
        <% end %>
        <% if can? :destroy, menu_item %>
          <td><%= link_to 'Destroy', menu_item_path(@menu, menu_item), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/ishmenu/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ishmenu</title>
  <%= stylesheet_link_tag    "ishmenu/application", media: "all" %>
  <%= javascript_include_tag "ishmenu/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>